### ISSUE TITLE
レシピでよく使われる食材トップ70

### ISSUE THREAD

**Issue by hanai-a** [michio-k/dlb-2018_team4#19]
会社からGO出たので共有します。

### 食材トップ50
えのき
エリンギ
かつお節
かぼちゃ
キャベツ
きゅうり
ごぼう
こんにゃく
しいたけ
しめじ
じゃがいも
しょうが
トマト
なす
にんじん
にんにく
パセリ
パン粉
ピーマン
ブロッコリー
ほうれん草
ミニトマト
もやし
レタス
レモン汁
塩昆布
牛乳
玉ねぎ
鶏ささみ
鶏むね肉（皮なし）
鶏もも肉（皮なし）
絹ごし豆腐
刻み海苔
小ねぎ（小口切り）
小松菜
小麦粉
青ねぎ
赤パプリカ
大根
大葉
鷹の爪
長ねぎ
豚もも薄切り肉
豚もも薄切り肉（脂身なし）
白ごま
白菜
片栗粉
木綿豆腐
油揚げ
卵
アボカド
えのき
エリンギ
オクラ
かいわれ大根
かつお節
カットわかめ
かぼちゃ
キャベツ
きゅうり
ごぼう
こんにゃく
さつまいも
しいたけ
しめじ
じゃがいも
しょうが
ツナ水煮缶
トマト
なす
にら
にんじん
にんにく
パセリ
パン粉
ピーマン
ピザ用チーズ
ひじき
ブロッコリー
ほうれん草
ミニトマト
もやし
レタス
レモン汁
れんこん
塩昆布
黄パプリカ
牛乳
玉ねぎ
鶏ささみ
鶏ひき肉
鶏むね肉（皮なし）
鶏もも肉（皮なし）
絹ごし豆腐
厚揚げ
刻み海苔
鮭
小ねぎ（小口切り）
小松菜
小麦粉
水菜
青ねぎ
赤パプリカ
大根
大葉
鷹の爪
長ねぎ
長芋
豚ひき肉
豚もも薄切り肉
豚もも薄切り肉（脂身なし）
白ごま
白菜
舞茸
粉チーズ
片栗粉
万能ねぎ
木綿豆腐
油揚げ
卵

**Comment by hanai-a** [comment]
「片栗粉」や「かつお節」は食材としてカウントしないと思うので、
トップ70で抽出しました。

**Comment by riow1983** [comment]
@hanai-a ありがとうございます。ここにある食材名称は食品成分表IDに対応した正規化された名称という理解でよろしいですか？

**Comment by riow1983** [comment]
#20 で画像を取得しました。
