### ISSUE TITLE
レシピ画像の整理

### ISSUE THREAD

**Issue by hanai-a** [michio-k/dlb-2018_team4#2]
レシピ画像の構成物
- 食器
- 材料
- 背景

目的：アウトプットの認識をあわせる

どのような傾向があるのか具体的に見ていきます。

**Comment by hanai-a** [comment]
## 味噌汁の例
接写せず、お椀が映るように遠くから撮っている。
材料よりも食器の領域が大きい傾向。

- 食器：お椀
- 材料：沈んでいるので少量しか見えない

![12627](https://user-images.githubusercontent.com/41976804/53620934-25b58900-3c38-11e9-9d42-8c5b8746b720.jpeg)
![26149](https://user-images.githubusercontent.com/41976804/53620935-264e1f80-3c38-11e9-9d95-903697fb4c7b.jpeg)
![26559](https://user-images.githubusercontent.com/41976804/53620936-264e1f80-3c38-11e9-82dd-3615f96b4b82.jpeg)

**Comment by riow1983** [comment]
料理画像とレシピ（料理作成手順）、それから材料リストは紐付いてるんでしたっけ？

**Comment by hanai-a** [comment]
> 料理画像とレシピ（料理作成手順）、それから材料リストは紐付いてるんでしたっけ？

はい、紐付いています

**Comment by hanai-a** [comment]
## 鍋の例
接写しており、鍋（食器）が映らない傾向。

![18948](https://user-images.githubusercontent.com/41976804/53645728-dba2c680-3c7c-11e9-828f-37b83042a3f8.jpeg)
![17990](https://user-images.githubusercontent.com/41976804/53645729-dc3b5d00-3c7c-11e9-8cc2-c54fc7f3b8c1.jpeg)
![18057](https://user-images.githubusercontent.com/41976804/53645732-dd6c8a00-3c7c-11e9-9a18-b9a5c27bea4e.jpeg)
![22979](https://user-images.githubusercontent.com/41976804/53645733-de052080-3c7c-11e9-8335-1fed2aa712f9.jpeg)

**Comment by hanai-a** [comment]
## ハンバーグの例
- 白い皿（食器）に乗っている傾向
- 付け合せの領域も大きい

![24188](https://user-images.githubusercontent.com/41976804/53646398-718b2100-3c7e-11e9-9b2a-57a549fd2d07.jpeg)
![10923](https://user-images.githubusercontent.com/41976804/53646400-7223b780-3c7e-11e9-937c-c4eb3d32249c.jpeg)
![11450](https://user-images.githubusercontent.com/41976804/53646404-7354e480-3c7e-11e9-8e1a-1a8face9a9fa.jpeg)


![12594](https://user-images.githubusercontent.com/41976804/53646408-751ea800-3c7e-11e9-8fda-512b76181c52.jpeg)
![12616](https://user-images.githubusercontent.com/41976804/53646411-764fd500-3c7e-11e9-8491-2621aba83b4b.jpeg)

**Comment by riow1983** [comment]
材料リストと作成手順（レシピ）が画像に紐付いているということであれば、入力された材料リストと出力側の材料リストとの類似度だけ計測すれば良い気がします。または材料リストをセンテンスト捉えて、doc2vecでセンテンス類似度を計測し、類似度の高い料理を出力するとか。例えば入力材料にカリフラワーがあったとすると、word embedding的にカリフラワーに近いブロッコリーを使った料理も出力料理に上がってくるようにしてレシピに「ブロッコリーはカリフラワーに代替可能」と記載するようにしても面白いかもしれません。

**Comment by riow1983** [comment]
出力側の材料リストは用意されているということなので、入力側の材料リストの準備が急務でしょうか。

**Comment by hanai-a** [comment]
レシピ画像は機械学習タスクに関係ないためクローズします
