### ISSUE TITLE
pre-trainedモデルとopenCVデフォルトカスケードファイルの使用可否について

### ISSUE THREAD

**Issue by riow1983** [michio-k/dlb-2018_team4#21]

**Comment by riow1983** [comment]
riow1983 [7:56 AM]
pre-trainedモデルの使用は不可という認識でよろしいでしょうか？そうだとして、openCVのデフォルトカスケードファイルも使用不可でしょうか？また詳細は木曜日（3/7）に改めて告知予定とのことでしたがzendeskにアップされていましたでしょうか？@sasakyu @frt03 @shinzis

**Comment by riow1983** [comment]
上記運営の３名に確認中。昨夜内一人より回答がありましたが決定打にかける回答でした。

> frt03 [10:06 PM]
僕には裁量が無いので公式な回答はお答えできかねますが、おそらく自己判断になると思われます。

**Comment by onouyek** [comment]
pre-trainedモデルは利用して問題ないとのこと

**Comment by riow1983** [comment]
運営側からは一向に明示的な返答がありません。自己判断で上記の通りとすると宣言しましたのでクローズとします。

**Comment by onouyek** [comment]
昨日、[回答](https://dlb-2018.slack.com/archives/CF7M255M1/p1552756649045100?thread_ts=1552258568.030300&cid=CF7M255M1)来ておりましたよ。

**Comment by riow1983** [comment]
通知が飛ばないので気づけませんでした。ありがとうございます。
