### ISSUE TITLE
データセット

### ISSUE THREAD

**Issue by onouyek** [michio-k/dlb-2018_team4#4]
- トレーニングデータセット概要

**Comment by onouek** [comment]
食材の分類は家庭でよく使うもの、トップ50の洗い出し

**Comment by riow1983** [comment]
#13 で準備が完了したのでクローズしていいと思いますがいかがでしょうか？

**Comment by onouyek** [comment]
[Open Image Dataset V4](https://storage.googleapis.com/openimages/web/index.html)の下記のデータを用いる
```
かぼちゃ
キャベツ
きゅうり
じゃがいも
トマト
にんじん
ピーマン
ブロッコリー
牛乳
大根
卵
きのこ
レモン
チーズ
```

**Comment by riow1983** [comment]
> #13 で準備が完了したのでクローズしていいと思いますがいかがでしょうか？
ここで収集した画像は学習に使用しないことにしました。onouekさんが上で上げているopen image datsetの画像を学習に使います。
