### ISSUE TITLE
機械学習モデルの作成

### ISSUE THREAD

**Issue by onouyek** [michio-k/dlb-2018_team4#6]

**Comment by riow1983** [comment]
READMEに書いた通り、入力画像（食材画像）から材料リストを取得するCNNモデルが必要と思われます。"the CNN model that detects and translates ingredients to texts"

**Comment by riow1983** [comment]
Google Cloud Vision APIなど、学習済みモデルを使えると嬉しい。

**Comment by riow1983** [comment]
とりあえず、スクレイピングで食材画像とラベルを拾う作業に取りかかった方が良いですね。

**Comment by riow1983** [comment]
スクレイピングは機械学習モデルの作成と別のissueとして独立させたほうが、チームの課題として共有しやすいと思います。私の方でissueを立てます。

**Comment by riow1983** [comment]
Open Image Dataset V4のアノテーション済みの画像データで学習させてカスタマイズしたモデルを構築し利用する

**Comment by riow1983** [comment]
- アノテーション済みの食材は以下の通り: [“かぼちゃ“, “キャベツ“, “きゅうり“, “じゃがいも“, “トマト“,  “にんじん“, “ピーマン“, “ブロッコリー“, “牛乳“, “大根“, “卵”,  “きのこ“, “レモン“, “チーズ“]
 - GoogleImageCrawlerで収集した画像はアノテーション作業をやっている余裕が無いため今回の学習には供さない
 - テスト画像は各自家庭の冷蔵庫にある食材(上記アノテーション済み食材に限る)を引っ張り出して写真を撮影する（ポスター用に最低３パターン欲しい）
