### ISSUE TITLE
参考事例

### ISSUE THREAD

**Issue by onouyek** [michio-k/dlb-2018_team4#8]

**Comment by onouyek** [comment]
> これ似てるのかな？<https://towardsdatascience.com/this-ai-is-hungry-b2a8655528be>
<sub>[View in Slack](https://dlb-2018.slack.com/archives/GFNPNNN7M/p1550478848004500)</sub>

**Comment by onouek** [comment]
> これ似てるのかな？<https://towardsdatascience.com/this-ai-is-hungry-b2a8655528be>
<sub>[View in Slack](https://dlb-2018.slack.com/archives/GFNPNNN7M/p1550478848004500)</sub>

**Comment by onouyek** [comment]
> <https://github.com/Murgio/Food-Recipe-CNN>
<sub>[View in Slack](https://dlb-2018.slack.com/archives/GFNPNNN7M/p1550478927004900)</sub>
