### ISSUE TITLE
the model that calculates the ingredient list similarity between the input list and the output list

### ISSUE THREAD

**Issue by riow1983** [michio-k/dlb-2018_team4#9]
入力画像から取得した材料リストとレシピに対応する材料リストを１対rest比較し、類似度を算出するモデルの作成が必要と思われます。

**Comment by riow1983** [comment]
で、これ私にやらせていただいてもよろしいですか？ @tanukiti1987 さん、output側の材料リストをいただきたいと思います。

**Comment by tanukiti1987** [comment]
申し訳ないですが、データのイメージをもう少し具体例でいただけたりしますでしょうか。 @riow1983

**Comment by riow1983** [comment]
入力リストとしてはこんな感じです。['アーティチョーク', 'アーモンド', 'アオベラ', 'アオヤギ', 'アカガイ', ...]

**Comment by tanukiti1987** [comment]
質問がよろしくなかった。。

> output側の材料リストをいただきたいと思います。

この材料のリストというのは、どういったイメージでしょうか？
レシピ画像を入力したときに出力される材料のリスト、つまり、入力写真と材料配列のセットが必要。という理解であってます。。？

**Comment by riow1983** [comment]
@tanukiti1987 さん、分かりにくくてすみません。入力側ではなく、出力側の材料リストをいただければと。料理画像ごとに定義された材料リストです。フローとしては、ユーザーが複数の食材をテーブルに乗せて写真を撮る→システムにアップロードする→システムが食材ごとに食材を検知し、食材の名称（テキスト）に変換(機械学習モデル)→入力材料リスト→類似モデルによるマッチング→**出力側の材料リスト**から類似度の高いリストをピックアップ→そのピックアップされた材料リストに紐づいたレシピと料理画像（ご提供いただく画像）を出力する、という想定です。ですので太字にした**出力側の材料リスト**をいただきたいと思います。
